apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: hazelcast-operator
  namespace: operators
spec:
  ## Manual Approve from 0.3.0
  installPlanApproval: Manual
  startingCSV: 0.3.0
  name: hazelcast-operator
  channel: alpha
  source: operatorhubio-catalog
  sourceNamespace: olm
  config:
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"